//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Count10DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class chart_of_accounts
    {
        public long id { get; set; }
        public string name { get; set; }
        public string alt_name { get; set; }
        public string predefined_name { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> nature_id { get; set; }
        public Nullable<long> organization_id { get; set; }
        public Nullable<bool> blsl { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> tag { get; set; }
        public string notes { get; set; }
        public Nullable<bool> system { get; set; }
        public Nullable<bool> reserved { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> archived { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
