//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Count10DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public long id { get; set; }
        public string name { get; set; }
        public string alt_name { get; set; }
        public string organization_id { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> currency_id { get; set; }
        public Nullable<long> stock_ledger_id { get; set; }
        public Nullable<long> manager_id { get; set; }
        public string kind { get; set; }
        public Nullable<bool> @virtual { get; set; }
        public Nullable<bool> inventoriable { get; set; }
        public Nullable<System.DateTime> status { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public string grade { get; set; }
        public string format { get; set; }
        public double area { get; set; }
        public Nullable<double> activity_area { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string photo { get; set; }
        public string remote_photo_url { get; set; }
        public string notes { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> archived { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
